### ISSUE TITLE
Invalid Pair errors

### ISSUE THREAD

**Issue by carels** [gfijrb/yobit-net-php-api#1]
Hi,

I keep getting "Invalid pair" errors when trying to get active orders / history:

var_dump($api_trade->ActiveOrders(
    (new \yobit\api\src\NonceCounter(NONCE_OUTPUT_DIR))->get(), array('pair' => 'ltc_btc')
));

Output:
object(stdClass)#3 (2) {
  ["success"]=>
  int(0)
  ["error"]=>
  string(12) "invalid pair"
}

var_dump($api_trade->TradeHistory(
    (new \yobit\api\src\NonceCounter(NONCE_OUTPUT_DIR))->get(), array('pair' => 'kbc_btc')
));

Output:
object(stdClass)#3 (2) {
  ["success"]=>
  int(0)
  ["error"]=>
  string(12) "invalid pair"
}

am I missing something in the way I am supposed to be calling the api?

**Comment by gfijrb** [comment]
Yes sorry fixed in [https://github.com/gfijrb/yobit-net-php-api/commit/39d404c6cc7e7e1db8b83ad8e9083a5da2104304]()
Your code is valide, please download last update.
Good luck.
